name = "openai-usage-tracker"
compatibility_date = "2025-10-16"
pages_build_output_dir = ".vercel/output/static"

# Node.js compatibility for Next.js API routes
compatibility_flags = ["nodejs_compat"]

# Note: Environment variables and secrets should be set via Cloudflare Pages dashboard
# Go to: Settings > Environment Variables
# Add OPENAI_ADMIN_KEY as a Secret for both Production and Preview environments

# Note: Headers configuration should be done in Cloudflare Pages dashboard
# Go to: Settings > Functions > _headers file (create in public folder if needed)
# Or configure via dashboard: Settings > Custom domains > Headers
