name = "openai-usage-tracker"
compatibility_date = "2025-10-16"
pages_build_output_dir = ".vercel/output/static"

# Node.js compatibility for Next.js API routes
compatibility_flags = ["nodejs_compat"]

# Environment variables for production
[env.production.vars]
# Note: OPENAI_ADMIN_KEY should be set via Cloudflare Pages dashboard as a secret
# Set it in: Settings > Environment Variables > Production

# Environment variables for preview/development
[env.preview.vars]
# Note: OPENAI_ADMIN_KEY should be set via Cloudflare Pages dashboard as a secret
# Set it in: Settings > Environment Variables > Preview

# Build configuration
[build]
command = "npm run build"

# Custom headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# API routes should not be cached
[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
